helmDefaults:
  createNamespace: true
  wait: true
  atomic: true
  timeout: 300

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: argocd
    url: https://argoproj.github.io/argo-helm
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts


releases:
  - name: tempo
    namespace: monitoring
    chart: ./charts/raw-manifests
    values:
      - helm-values/tempo.yaml

  - name: opentelemetry-collector
    namespace: monitoring
    chart: ./charts/raw-manifests
    values:
      - helm-values/opentelemetry-collector.yaml
    needs:
      - monitoring/tempo

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.11.3"
    values:
      - helm-values/nginx.yaml
    needs:
      - monitoring/opentelemetry-collector

  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager
    version: "1.18.2"
    values:
      - helm-values/cert-manager.yaml
    needs: 
      - ingress-nginx/ingress-nginx

  - name: cluster-issuer
    namespace: cert-manager
    chart: ./charts/raw-manifests
    values:
      - helm-values/cluster-issuer.yaml
    needs:
      - cert-manager/cert-manager

  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: "1.19.0"
    values:
      - helm-values/external-dns.yaml
    needs: 
      - ingress-nginx/ingress-nginx
      
  - name: argocd
    namespace: argocd
    chart: argocd/argo-cd
    version: "9.0.5" 
    values:
      - helm-values/argocd.yaml
    needs: 
      - ingress-nginx/ingress-nginx
      - external-dns/external-dns
      - cert-manager/cluster-issuer

  - name: blackbox-exporter
    namespace: monitoring
    chart: prometheus/prometheus-blackbox-exporter
    values:
      - helm-values/blackbox-exporter.yaml
    needs:
      - ingress-nginx/ingress-nginx

  - name: loki
    namespace: monitoring
    chart: ./charts/raw-manifests
    values:
      - helm-values/loki.yaml

  - name: fluent-bit
    namespace: monitoring
    chart: ./charts/raw-manifests
    values:
      - helm-values/fluent-bit.yaml
    needs:
      - monitoring/loki

  - name: prometheus
    namespace: monitoring
    chart: prometheus/prometheus
    values:
      - helm-values/prometheus.yaml
    needs:
      - monitoring/blackbox-exporter
      - ingress-nginx/ingress-nginx
      - external-dns/external-dns
      - cert-manager/cluster-issuer

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - helm-values/grafana.yaml
    needs:
      - monitoring/loki
      - monitoring/prometheus
      - ingress-nginx/ingress-nginx
      - external-dns/external-dns
      - cert-manager/cluster-issuer

  - name: grafana-cloud-traces-dashboard
    namespace: monitoring
    chart: ./charts/raw-manifests
    values:
      - helm-values/grafana-cloud-traces-dashboard.yaml
    needs:
      - monitoring/grafana

  - name: grafana-kubernetes-infra-dashboard
    namespace: monitoring
    chart: ./charts/raw-manifests
    values:
      - helm-values/kubernetes-infra-dashboard.yaml
    needs:
      - monitoring/grafana

  - name: grafana-otel-traces-datasource
    namespace: monitoring
    chart: ./charts/raw-manifests
    values:
      - helm-values/grafana-otel-traces-datasource.yaml
    needs:
      - monitoring/grafana
      - monitoring/tempo

  - name: grafana-cloud-traces-datasource
    namespace: monitoring
    chart: ./charts/raw-manifests
    values:
      - helm-values/grafana-cloud-traces-datasource.yaml
    needs:
      - monitoring/grafana

  - name: postgres
    namespace: app
    chart: bitnami/postgresql
    version: "16.7.27"
    values:
      - helm-values/postgres.yaml

  - name: redis
    namespace: app
    chart: bitnami/redis
    version: "20.11.3"
    values:
      - helm-values/redis.yaml

  - name: api-gateway
    namespace: app
    chart: ./charts/app
    values:
      - helm-values/app/api-gateway.yaml
    needs:
      - app/redis
      - ingress-nginx/ingress-nginx
      - external-dns/external-dns
      - cert-manager/cluster-issuer

  - name: dashboard-api
    namespace: app
    chart: ./charts/app
    values:
      - helm-values/app/dashboard-api.yaml
    needs:
      - app/postgres

  - name: inventory-service
    namespace: app
    chart: ./charts/app
    values:
      - helm-values/app/inventory-service.yaml
    needs:
      - app/postgres

  - name: notification-service
    namespace: app
    chart: ./charts/app
    values:
      - helm-values/app/notification-service.yaml
    needs:
      - app/postgres

  - name: order-service
    namespace: app
    chart: ./charts/app
    values:
      - helm-values/app/order-service.yaml
    needs:
      - app/postgres

  - name: payment-service
    namespace: app
    chart: ./charts/app
    values:
      - helm-values/app/payment-service.yaml
    needs:
      - app/postgres

  - name: scheduler
    namespace: app
    chart: ./charts/app
    values:
      - helm-values/app/scheduler.yaml
    needs:
      - app/postgres

  - name: shipping-service
    namespace: app
    chart: ./charts/app
    values:
      - helm-values/app/shipping-service.yaml
    needs:
      - app/postgres

  - name: worker
    namespace: app
    chart: ./charts/app
    values:
      - helm-values/app/worker.yaml
    needs:
      - app/order-service
      - app/payment-service
      - app/shipping-service
